-- MySQL Script generated by MySQL Workbench
-- 08/04/15 15:56:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pichangamaker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pichangamaker` ;

-- -----------------------------------------------------
-- Schema pichangamaker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pichangamaker` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pichangamaker` ;

-- -----------------------------------------------------
-- Table `pichangamaker`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `lat` VARCHAR(20) NULL,
  `lng` VARCHAR(20) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`Login` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`Login` (
  `user` VARCHAR(25) NOT NULL,
  `pass` BLOB NULL,
  `verified` TINYINT(1) NULL,
  `token` VARCHAR(200) NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`Persona` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(10) NULL,
  `nombre` VARCHAR(100) NULL,
  `telefono` VARCHAR(15) NULL,
  `idEmpresa` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `user` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idPersona`, `user`),
  INDEX `fk_Persona_Empresa1_idx` (`idEmpresa` ASC),
  INDEX `fk_Persona_login1_idx` (`user` ASC),
  CONSTRAINT `fk_Persona_Empresa1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `pichangamaker`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_login1`
    FOREIGN KEY (`user`)
    REFERENCES `pichangamaker`.`Login` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`Pichanga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`Pichanga` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`Pichanga` (
  `idPichanga` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NULL,
  `precio` DOUBLE NULL,
  `modoPago` VARCHAR(45) NULL,
  `fechaInicio` DATETIME NULL,
  `fechaFin` DATETIME NULL,
  `idPersona` INT NOT NULL,
  `minIntegrantes` INT NULL,
  `maxIntegrantes` INT NULL,
  `observaciones` VARCHAR(120) NULL,
  `lugar` VARCHAR(200) NULL,
  `isPrivate` TINYINT(1) NULL,
  `lat` VARCHAR(20) NULL,
  `lng` VARCHAR(20) NULL,
  PRIMARY KEY (`idPichanga`),
  INDEX `fk_Pichanga_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Pichanga_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `pichangamaker`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`Asistentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`Asistentes` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`Asistentes` (
  `idPichanga` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `pagoRealizado` DOUBLE NULL,
  `observaciones` VARCHAR(120) NULL,
  PRIMARY KEY (`idPichanga`, `idPersona`),
  INDEX `fk_Asistencia_Pichanga_idx` (`idPichanga` ASC),
  INDEX `fk_Asistencia_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Asistencia_Pichanga`
    FOREIGN KEY (`idPichanga`)
    REFERENCES `pichangamaker`.`Pichanga` (`idPichanga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `pichangamaker`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`ChatLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`ChatLine` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`ChatLine` (
  `idChatLine` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `texto` VARCHAR(500) NULL,
  `room` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `user` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idChatLine`, `idPersona`, `user`),
  INDEX `fk_ChatLine_Pichanga1_idx` (`room` ASC),
  INDEX `fk_ChatLine_Persona1_idx` (`idPersona` ASC, `user` ASC),
  CONSTRAINT `fk_ChatLine_Pichanga1`
    FOREIGN KEY (`room`)
    REFERENCES `pichangamaker`.`Pichanga` (`idPichanga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChatLine_Persona1`
    FOREIGN KEY (`idPersona` , `user`)
    REFERENCES `pichangamaker`.`Persona` (`idPersona` , `user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pichangamaker`.`ConnectionHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pichangamaker`.`ConnectionHistory` ;

CREATE TABLE IF NOT EXISTS `pichangamaker`.`ConnectionHistory` (
  `idPersona` INT NOT NULL,
  `user` VARCHAR(25) NOT NULL,
  `idPichanga` INT NOT NULL,
  `lastConnection` DATETIME NULL,
  PRIMARY KEY (`idPersona`, `user`, `idPichanga`),
  INDEX `fk_ConnectionHistory_Pichanga1_idx` (`idPichanga` ASC),
  CONSTRAINT `fk_ConnectionHistory_Persona1`
    FOREIGN KEY (`idPersona` , `user`)
    REFERENCES `pichangamaker`.`Persona` (`idPersona` , `user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectionHistory_Pichanga1`
    FOREIGN KEY (`idPichanga`)
    REFERENCES `pichangamaker`.`Pichanga` (`idPichanga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



SET FOREIGN_KEY_CHECKS=0;
SET autocommit = true;